"""add table_number to matches

Revision ID: 22fc4735b24d
Revises: 5e4868f58289
Create Date: 2026-03-02 22:31:11.219798

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '22fc4735b24d'
down_revision: Union[str, Sequence[str], None] = '5e4868f58289'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('matches', sa.Column('table_number', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('matches', 'table_number')
    # ### end Alembic commands ###
