"""Add status field to tournaments

Revision ID: 5e4868f58289
Revises: 7a9a42c2fef5
Create Date: 2026-02-25 18:59:58.721796

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5e4868f58289'
down_revision: Union[str, Sequence[str], None] = '7a9a42c2fef5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # Add column as nullable first
    op.add_column('tournaments', sa.Column('status', sa.String(), nullable=True))
    # Set default value for existing rows
    op.execute("UPDATE tournaments SET status = 'ACTIVE'")
    # Make it NOT NULL
    op.alter_column('tournaments', 'status', nullable=False)


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('tournaments', 'status')
    # ### end Alembic commands ###
